micronaut:
  application:
    name: employeeService
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
datasources:
  default:
    url: jdbc:mariadb://localhost:3306/employees
    driverClassName: org.mariadb.jdbc.Driver
    username: dbuser
    password: dbpass
    schema-generate: NONE
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: none
flyway:
  datasources:
    default:
      enabled: true
      locations:
        - classpath:db/migration
jackson.serialization.writeDatesAsTimestamps: false
