version: '3.8'

services:
  employee-db:
    image: mariadb:10.5
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=t0p$ecret
      - MYSQL_DATABASE=employees
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
    networks:
      employee-app:
        aliases:
          - employee-db
    volumes:
      - ./data/:/var/lib/mysql
  employee-service:
    image: employee-service:latest
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=employee-db
      - DATABASE_PORT=3306
      - DATASOURCES_DEFAULT_URL=jdbc:mariadb://employee-db:3306/employees
    networks:
      employee-app:
        aliases:
          - employee-service
networks:
  employee-app:
